image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cp finmodel-workbook.html public/index.html
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
